name: Continuous integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependences
        run: npm install
      - name: Run tests
        run: |
          npm start &
          sleep 2      
          npm test